### ISSUE TITLE
mt76:rx_aggre_stop

### ISSUE THREAD

**Issue by ohquait** [openwrt/mt76#388]
today updated master clone:

/var/lib/dkms/mt76xx/0.1.0-6pclos2020/build/agg-rx.c: In function ‘mt76_rx_aggr_stop’:
/var/lib/dkms/mt76xx/0.1.0-6pclos2020/build/agg-rx.c:293:2: error: implicit declaration of function ‘rcu_swap_protected’ [-Werror=implicit-function-declaration]
  293 |  rcu_swap_protected(wcid->aggr[tidno], tid,
      |  ^~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [scripts/Makefile.build:268: /var/lib/dkms/mt76xx/0.1.0-6pclos2020/build/agg-rx.o] Error 1
make[1]: *** [Makefile:1675: /var/lib/dkms/mt76xx/0.1.0-6pclos2020/build] Error 2
make[1]: Leaving directory '/usr/src/kernel-devel-5.6.3-pclos1'
make: *** [Makefile:51: all] Error 2

ok, i use a different makefile, but this is not the error-maker

**Comment by ohquait** [comment]
on master/agg-rx.c
old: at line 289
void mt76_rx_aggr_stop(struct mt76_dev *dev, struct mt76_wcid *wcid, u8 tidno)
{
	struct mt76_rx_tid *tid;

	rcu_read_lock();

	tid = rcu_dereference(wcid->aggr[tidno]);
	if (tid) {
		rcu_assign_pointer(wcid->aggr[tidno], NULL);
		mt76_rx_aggr_shutdown(dev, tid);
		kfree_rcu(tid, rcu_head);
	}

	rcu_read_unlock();
}
EXPORT_SYMBOL_GPL(mt76_rx_aggr_stop);

new: at line 289
void mt76_rx_aggr_stop(struct mt76_dev *dev, struct mt76_wcid *wcid, u8 tidno)
{
	struct mt76_rx_tid *tid;

	rcu_read_lock();

	tid = rcu_dereference(wcid->aggr[tidno]);
	if (tid) {
		rcu_assign_pointer(wcid->aggr[tidno], NULL);
		mt76_rx_aggr_shutdown(dev, tid);
		kfree_rcu(tid, rcu_head);
	}

	rcu_read_unlock();
}
EXPORT_SYMBOL_GPL(mt76_rx_aggr_stop);


that's fixed the problem
master/agg-rx.c

now the drivers compiled good

**Comment by ohquait** [comment]
works on kernel-5.6.3-pclos3 also
