### ISSUE TITLE
Cannot build on 4.4.y

### ISSUE THREAD

**Issue by JpegXguy** [openwrt/mt76#497]
Trying to install on Armbian with kernel version `4.4.213-rockchip64` with `dkms install` using the `dkms.conf` suggested on https://github.com/openwrt/mt76/issues/276#issuecomment-48548264.
Build fails with the log:

```
DKMS make.log for mt76-1 for kernel 4.4.213-rockchip64 (aarch64)
Τετ 27 Ιαν 2021 10:04:24 μμ EET
make: Entering directory '/usr/src/linux-headers-4.4.213-rockchip64'
  CC [M]  /var/lib/dkms/mt76/1/build/mmio.o
  CC [M]  /var/lib/dkms/mt76/1/build/util.o
  CC [M]  /var/lib/dkms/mt76/1/build/trace.o
  CC [M]  /var/lib/dkms/mt76/1/build/dma.o
In file included from /var/lib/dkms/mt76/1/build/mt76.h:28,
                 from /var/lib/dkms/mt76/1/build/mmio.c:17:
/var/lib/dkms/mt76/1/build/util.h:20:10: fatal error: linux/bitfield.h: Δεν υπάρχει τέτοιο αρχείο ή κατάλογος
 #include <linux/bitfield.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [scripts/Makefile.build:277: /var/lib/dkms/mt76/1/build/mmio.o] Error 1
make[1]: *** Waiting for unfinished jobs....
In file included from /var/lib/dkms/mt76/1/build/mt76.h:28,
                 from /var/lib/dkms/mt76/1/build/dma.c:18:
/var/lib/dkms/mt76/1/build/util.h:20:10: fatal error: linux/bitfield.h: Δεν υπάρχει τέτοιο αρχείο ή κατάλογος
 #include <linux/bitfield.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [scripts/Makefile.build:277: /var/lib/dkms/mt76/1/build/dma.o] Error 1
In file included from /var/lib/dkms/mt76/1/build/mt76.h:28,
                 from /var/lib/dkms/mt76/1/build/util.c:18:
/var/lib/dkms/mt76/1/build/util.h:20:10: fatal error: linux/bitfield.h: Δεν υπάρχει τέτοιο αρχείο ή κατάλογος
 #include <linux/bitfield.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [scripts/Makefile.build:277: /var/lib/dkms/mt76/1/build/util.o] Error 1
In file included from /var/lib/dkms/mt76/1/build/mt76.h:28,
                 from /var/lib/dkms/mt76/1/build/trace.h:21,
                 from /var/lib/dkms/mt76/1/build/trace.c:21:
/var/lib/dkms/mt76/1/build/util.h:20:10: fatal error: linux/bitfield.h: Δεν υπάρχει τέτοιο αρχείο ή κατάλογος
 #include <linux/bitfield.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [scripts/Makefile.build:277: /var/lib/dkms/mt76/1/build/trace.o] Error 1
make: *** [Makefile:1488: _module_/var/lib/dkms/mt76/1/build] Error 2
make: Leaving directory '/usr/src/linux-headers-4.4.213-rockchip64'
```

Assuming it's because the header `include/linux/bitfield.h` [doesn't exist in 4.4.y](https://elixir.bootlin.com/linux/v4.4.213/source/include/linux/bitfield.h).
Is there a branch/tag/commit, or patch I can use to compile on 4.4.y?

**Comment by nbd168** [comment]
Building on these old kernels is not supported
